version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    container_name: speer-notes-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongodb_data:/.data/db

volumes:
  mongodb_data: